### ISSUE TITLE
opacity 는 정말 reflow 가 안일어나요 ?

### ISSUE THREAD

**Issue by yunseorim1116** [fe-drilling/gurren-lagann#3]
# 정답 : opacity 속성 값에 따라 다릅니다.

## case 1
opacity: 0 -> opaciy: 1
=> reflow 발생

![](https://velog.velcdn.com/images/seorim6417/post/f99ceacf-58b5-4f91-8fcd-c7806bcd45a5/image.png)

## case 2
opacity: 0 -> opaciy: 0.5
=> reflow 발생하지 않음
![](https://velog.velcdn.com/images/seorim6417/post/37cbb788-8e98-4478-8de2-737d26437689/image.png)

## 확인하는 방법
퍼포먼스탭 => 녹화=> layout 검색
출처 : https://sypear.tistory.com/32

## 왜 ? 
Using opacity with a value other than 1 places the element in a new stacking context.

위 설명처럼 opacity의 값으로 1이 아닌 다른 값을 사용하면 새로운 stacking context에 놓이게 되기 때문입니다. stacking context을 생성하면서 다시 렌더링하는 과정에서 계층이 구분되어 있어 layout을 고려할 필요가 없기 때문에 reflow가 발생하지 않습니다.

#### Stacking context
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context

## 나는 죽어도 opacity 를 쓰고 싶어요!
애니메이션 효과를 내기 위해 opacity 를 사용해야 할 일이 생길 때가 있습니다. reflow 를 방지 하고 싶다면 will-change: opacity 속성을 붙여주시거나 0.99로 값을 주는 것이 좋겠습니다.

**Comment by havenothorn** [comment]
will-change 사용은 성능 문제 해결의 최후의 수단으로 생각해야할 것 같습니다. 공식 문서에도 경고를 하고 있습니다.

will-change is intended to be used as something of a last resort, in order to try to deal with existing performance problems.

또한 말씀해주신 will-change : opacity과 관련한 경고도 포함되어 있습니다.

Be aware, that will-change may actually influence the visual appearance of elements, when used with property values, that create a stacking context(e.g. will-change: opacity), as the stacking context is created up front.

이처럼 Stacking Context를 생성하는 속성 값(ex: opacity)의 경우 시각적 표현에 오히려 안좋은 영향을 미칠 수 있다는 점에 유의해야할 것 같습니다.

**will-change**
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change
